apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: flask-app2:1.1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
        # <-- ПРОБИ -->
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

